spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password: password
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: superpupersecretpassword

server:
  port: 8081