spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true

  server:
    port: 8084






#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    password: password
#    driver-class-name: org.h2.Driver
#    username: sa
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#jwt:
#  secret: superpupersecretpassword
#
#server:
#  port: 8081